name: Build and push
on:
  push:
    branches: [main]
jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y sox libsox-fmt-mp3
      - uses: nschloe/action-cached-lfs-checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist
  deploy-itch:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: igua-rpg
          ITCH_USER: hubol
          PACKAGE: build
  deploy-heroku:
    needs: build
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - run: >
          git config --global user.email "hubol.gordon@gmail.com" &&
          git config --global user.name "hubol"
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: hubol.gordon@gmail.com
          justlogin: true
      - run: >
          git init &&
          heroku git:remote -a igua-rpg
      - uses: actions/download-artifact@v2
        with:
          name: build
      # https://izy.codes/heroku-deploy-static-html-en/
      - run: >
          echo '<?php include_once("index.html"); ?>' > index.php &&
          echo '{}' > composer.json
      - run: >
          git add . &&
          git commit -am "${{ github.event.commits[0].message }}" &&
          git push heroku master -f
  cleanup:
    needs: [deploy-itch, deploy-heroku]
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: build
