name: Build and push
on:
  push:
    branches: [main]
jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y sox libsox-fmt-mp3
      - uses: nschloe/action-cached-lfs-checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist
  build-win:
    runs-on: windows-2019
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          repository: hubol/electric-lizard
      - uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'icon.png'
          fileDir: './'
          encodedString: iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAMAAABrrFhUAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAMAUExURQAAAMwsQplXr8yuCv///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsv/VAAAAEAdFJOU////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////wBT9wclAAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAGXRFWHRTb2Z0d2FyZQBwYWludC5uZXQgNC4wLjIx8SBplQAABAZJREFUeF7tnUFywyAQBO04//9ycjWkSl1Ti0GQ1nURSMNML/IheTzh+jn8eiiADrhW4PAE/BgBGSADZMClAkLwcAXsAnYBu4BdwC5wpcDhTYC/BXpxThME26ACdArogMMUMAJ0EpQBMqBV4DAEeA4QgkIwVEAGHKaADAgT8DzMALbBOAKnHY0VIGWADjjs48gIGIGiArufC4xA0QDbnwx1gA4oKiAEN1dABhQTYBfYPAH5DyLkmN0EKTNg989jBSBLp3UjsJkCRiC1OI3fzAC2QSNAlk7rRmAzBYxAanEav5kB7AJGgCyd1o3AZgoYgdTiNH4zA9gFjABZOq0bgc0UMAKpxWn8ZgawCxgBsnRaNwKbKWAEUovT+M0MYBeII/BafI12mAJQpvv6YgO8dMBgBYyAEQgVkAGLFRiMgPwgtPj97QI6YLACtsGwCTxlwGIFBifALiAD7va1V01YGpE/Dqg+wOr7FSBUQAfIgE6B1Rmurh8m4O85oPoAq+9XgFABISgEhWCrwGqIVdcPEWAXEIJC8L9DsAqdu99PUHzc/QWqz6cAoIAOqFrs7vcbASNwrYAMuHuGq88nA2SADLhUQAhWIXP3+4WgELwZBL/hSiOVztfLMR2C6QOTIOl8CtApoAPIYqPrqWVp/XQ+I2AEWgVkAGVsdD3NLK2fzicDZIAMaBQQggSZ0fUUWrR+Op8QFIKTIUgWpXofARpP9ekRoAeiugJ0CpBgVNcBsyFIO0J1I2AEWgXIMVSXATLAg9Dcr0HKJNXtAnYBu0CjAEWG6rZB2+CH2yBZMK2P7gL9+sN/FE1fkMYrwOA2qAM6BYwA/e6e1inTaV0GyICxR2EhKARbBewCKeVpfEp5Gm8XsAvYBYb+IGIbXN0Gv8Krh2B4+xdBdnobTF9AAToFUgF1AChgBOhkl9bJcqmFZYAMaBVIHUSOlAFpxmk8KZ7uoAyQATKgUSCNEEVSCBLU0jopnu6gEBSCQlAIviuQMoSYZBdIKU/jSfF0B+0CdgG7gF3ALvCmQApRgrJtkNpaWifF0x20DdoGbYO2waPaIEGyr/cQTO+n8dPbID2QAnQK6IBOgdRBNN4IpCc9Gk+Kp3UjYARaBVIH0XgZQJlO66R4WpcBMkAGNAqkEaLxQjCFHI0nxdO6ENwNgtUdI4eNnn84A0Y/IAlSjZQCkMLVenWHaP3q/DqAFK7WqztE61fn1wGkcLVe3SFavzq/DiCFq/XqDtH61fl1AClcrVd3iNavzq8DSOFqvbpDtH51fh1AClfr1R2i9avzf9wB9AKz69P/pObsF6T1FGD23xSlHZld1wE64MN/VXa2pdP1jIARMAJz/79AmtFPj5cBMkAGyIB3Bf795/Av2d3QZhButzwAAAAASUVORK5CYII=
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
        env:
          APP_ID: hubol.igua-rpg
          PRODUCT_NAME: IguaRPG
      - uses: actions/upload-artifact@v2
        with:
          name: build-win
          path: dist/win
  deploy-itch:
    needs: [build, build-win]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - uses: actions/download-artifact@v2
        with:
          name: build-win
          path: build-win
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: igua-rpg
          ITCH_USER: hubol
          PACKAGE: build
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: win
          ITCH_GAME: igua-rpg
          ITCH_USER: hubol
          PACKAGE: build-win
  deploy-heroku:
    needs: build
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - run: >
          git config --global user.email "hubol.gordon@gmail.com" &&
          git config --global user.name "hubol"
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: hubol.gordon@gmail.com
          justlogin: true
      - run: >
          git init &&
          heroku git:remote -a igua-rpg
      - uses: actions/download-artifact@v2
        with:
          name: build
      # https://izy.codes/heroku-deploy-static-html-en/
      - run: >
          echo '<?php include_once("index.html"); ?>' > index.php &&
          echo '{}' > composer.json
      - run: >
          git add . &&
          git commit -am "${{ github.event.commits[0].message }}" &&
          git push heroku master -f
  cleanup:
    needs: [deploy-itch, deploy-heroku]
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            build
            build-win
